Do_an_01/urls.py
from django.urls import path
from Do_an_01 import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'Do_an_01'
urlpatterns = [
    path('Masterbase.html', views.Masterbase),
    path('', views.index, name='index'),
    path('single/<int:pk>/', views.single, name='single'),
    path('book/<int:pk>/', views.book, name='book'),
    path('category/<int:pk>/', views.category, name='category'),
    path('search/', views.search, name='search'),
    path('contact/', views.contact_hdg, name='contact'),
    path('storys_service/', views.storys_service, name='storys_service'),
    path('story_service/<int:pk>/', views.story_service, name='story_service'),

]

Do_an_ck_01/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf import settings

# API
from rest_framework import routers
from Do_an_01.views import StorytViewSet
router = routers.DefaultRouter()
router.register('story', StorytViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Do_an_01.urls')),
    path('', include('customers_hdg.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),

]
# Static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers_hdg/urls.py
from django.urls import path
from customers_hdg import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'customers_hdg'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('my-account/', views.my_account, name='my_account'),
    path('logout/', views.logout, name='logout'),

]

Do_an_01/models.py
from django.db import models
import datetime
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Story(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=250, unique=True)
    author = models.CharField(max_length=250)
    url = models.URLField(unique=True)
    content = RichTextUploadingField(blank=True)
    public_day = models.DateField(default=datetime.date.today)
    image = models.ImageField(upload_to='Do_an_01/img', default='Do_an_01/img/logo.jpg')

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    subject = models.CharField(max_length=400)
    message = models.TextField()
    submit_day = models.DateField(default=datetime.date.today)

    def __str__(self):
        return self.subject

class Subcribe(models.Model):
    email = models.CharField(max_length=254)
    subcribe_day = models.DateField()

class Comment(models.Model):
    post = models.ForeignKey(Story, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


class Book(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=250, unique=True)
    author = models.CharField(max_length=250)
    url = models.URLField(unique=True)
    content = RichTextUploadingField(blank=True)
    public_day = models.DateField(default=datetime.date.today)
    image = models.ImageField(upload_to='Do_an_01/img', default='Do_an_01/img/logo.jpg')

    def __str__(self):
        return self.name

Do_an_01/forms.py
from django import forms
from Do_an_01 import models


class FormContact(forms.ModelForm):
    name = forms.CharField(label='Name', max_length=150, widget=forms.TextInput(attrs={
        "class": "form-control fh5co_contact_text_box",
        "placeholder": "Enter Your Name",
        "required": "required",
    }))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={
        "class": "form-control fh5co_contact_text_box",
        "placeholder": "Email",
        "required": "required",
    }))
    subject = forms.CharField(label='Subject', max_length=400, widget=forms.TextInput(attrs={
        "class": "form-control fh5co_contact_text_box",
        "placeholder": "Subject",
        "required": "required",
    }))
    message = forms.CharField(label='Message', widget=forms.Textarea(attrs={
        "class": "form-control fh5co_contacts_message",
        "placeholder": "Message",
        "required": "required",
    }))

    class Meta:
        model = models.Contact
        fields = '__all__'
        exclude = ['submit_day']

Do_an_01/views.py
from django.shortcuts import render, redirect
from Do_an_01.models import Category, Story, Book
import re
from Do_an_01.forms import FormContact
from Do_an_01.my_module import *

from Do_an_ck_01.settings import EMAIL_HOST_USER
from django.core.mail import EmailMessage

# API
from django.http import JsonResponse
from rest_framework import viewsets, permissions
from Do_an_01.serializers import StorySerializer

# Phân trang
from django.core.paginator import Paginator


def Masterbase(request):
    return render(request, 'Do_an_01/Masterbase.html', {
        'story_newest_3': story_newest_3,
    })


# Biến toàn cục
story_list = Story.objects.order_by('-public_day')

# Thể loại
list_category = Category.objects.all()

# Slide
story_newest_14 = story_list[0:6]

# Lọc hiển thị nội dung footer
story_newest_3 = story_list[0:5]

# Sách
sach_hay = Book.objects.filter(category=9).order_by('-public_day')[0:10]

# Tin tức
tin_tuc = Story.objects.filter(category=3).order_by('-public_day')[0:7]


def index(request):
    # Kiểm tra trạng thái đăng nhập của người dùng
    session_status = check_session(request, 'sessionNguoiDung')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionNguoiDung')
    story_newest_1 = story_list[0]
    story_newest_4 = story_list[1:5]
    # Nhà đất bán
    nha_dat_ban = Story.objects.filter(category=1).order_by('-public_day')[0:6]
    # Nhà đất thuê
    nha_dat_thue = Story.objects.filter(category=2).order_by('-public_day')[0:7]
    return render(request, 'Do_an_01/index.html', {
        'story_newest_1': story_newest_1,
        'story_newest_4': story_newest_4,
        'story_newest_14': story_newest_14,
        'nha_dat_ban': nha_dat_ban,
        'nha_dat_thue': nha_dat_thue,
        'tin_tuc': tin_tuc,
        'list_category': list_category,
        'story_newest_3': story_newest_3,
        'session_status': session_status,
        'session_info': session_info,
        'sach_hay': sach_hay,
    })


def category(request, pk):
    # Kiểm tra trạng thái đăng nhập của người dùng
    session_status = check_session(request, 'sessionNguoiDung')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionNguoiDung')

    # Phân trang Story
    story_list = Story.objects.filter(category=pk).order_by('-public_day')
    paginator = Paginator(story_list, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Phân trang Book
    book_list = Book.objects.filter(category=pk).order_by('-public_day')
    paginator = Paginator(book_list, 6)
    page_number = request.GET.get('page')
    page_obj_book = paginator.get_page(page_number)

    category_name = Category.objects.get(pk=pk)
    return render(request, 'Do_an_01/category.html', {
        'story_list': story_list,
        'category_name': category_name,
        'list_category': list_category,
        'page_obj': page_obj,
        'story_newest_3': story_newest_3,
        'session_status': session_status,
        'session_info': session_info,
        'tin_tuc': tin_tuc,
        'page_obj_book': page_obj_book,

    })


def contact_hdg(request):
    # Kiểm tra trạng thái đăng nhập của người dùng
    session_status = check_session(request, 'sessionNguoiDung')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionNguoiDung')
    else:
        return redirect('customers_hdg:login')
    # Liên hệ
    form = FormContact()
    result_contact = ''
    if request.POST.get('btnSendContact'):
        form = FormContact(request.POST)
        if form.is_valid():
            request.POST._mutable = True
            post = form.save(commit=False)
            post.name = form.cleaned_data['name']
            post.email = form.cleaned_data['email']
            post.subject = form.cleaned_data['subject']
            post.message = form.cleaned_data['message']
            post.save()
            # Gửi mail
            content = '<p>Chào bạn <b>' + post.name + '</b></p>'
            content += '<p>Chúng tôi đã nhận được thông tin của bạn thông quan Website Phú yên News với nội dung như sau:</p>'
            content += '<p>' + post.message + '</p>'
            content += '<p>Chúng tôi sẽ liên hệ bạn trong thời gian sớm nhất.</p>'
            content += '<p>Trân trọng.</p>'
            # Không có html
            # send_mail(subject, content, EMAIL_HOST_USER, [email])
            # Có định dạng html
            msg = EmailMessage(post.subject, content, EMAIL_HOST_USER, [post.email])
            msg.content_subtype = 'html'
            msg.send()
            result_contact = '''
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    Gửi thông tin thành công. Cảm ơn bạn đã liên hệ. Chúng tôi sẽ phản hồi trong thời gian sớm nhất.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                '''
        else:
            result_contact = '''
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    Gửi thông tin thất bại.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                '''
    return render(request, 'Do_an_01/contact_hdg.html', {
        'result_contact': result_contact,
        'form': form,
        'list_category': list_category,
        'story_newest_3': story_newest_3,
        'session_status': session_status,
        'session_info': session_info,
    })


def single(request, pk):
    # Kiểm tra trạng thái đăng nhập của người dùng
    session_status = check_session(request, 'sessionNguoiDung')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionNguoiDung')
    story = Story.objects.get(pk=pk)
    return render(request, 'Do_an_01/single.html', {
        'story': story,
        'story_newest_3': story_newest_3,
        'list_category': list_category,
        'session_status': session_status,
        'session_info': session_info,
        'tin_tuc': tin_tuc,
    })


def book(request, pk):
    # Kiểm tra trạng thái đăng nhập của người dùng
    session_status = check_session(request, 'sessionNguoiDung')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionNguoiDung')
    book = Book.objects.get(pk=pk)
    return render(request, 'Do_an_01/book.html', {
        'book': book,
        'story_newest_3': story_newest_3,
        'list_category': list_category,
        'session_status': session_status,
        'session_info': session_info,
        'sach_hay': sach_hay,
    })


def search(request):
    # Kiểm tra trạng thái đăng nhập của người dùng
    session_status = check_session(request, 'sessionNguoiDung')
    session_info = ''
    if session_status:
        session_info = request.session.get('sessionNguoiDung')
    # Tìm theo Story
    story_list = []
    book_list = []
    tu_khoa = ''
    if request.GET.get('keyword'):
        # Gán biến
        tu_khoa = request.GET.get('keyword')

        # Lọc theo từ khóa và xử lý loại bỏ html
        Do_an_01 = Story.objects.all().values()
        Do_an_02 = Book.objects.all().values()
        lst_story = list(Do_an_01)
        lst_book = list(Do_an_02)
        id_list = []
        id_book= []
        for story in lst_story:
            story['content'] = re.sub('<[^<]+?>', '', story['content'])
            if tu_khoa.lower() in story['name'].lower() or tu_khoa.lower() in story['content'].lower():
                id_list.append(story['id'])

        for book in lst_book:
            book['content'] = re.sub('<[^<]+?>', '', book['content'])
            if tu_khoa.lower() in book['name'].lower() or tu_khoa.lower() in book['content'].lower():
                id_book.append(book['id'])

        # Lọc Do_an_01 theo danh sách id đã tìm.
        story_list = Story.objects.filter(id__in=id_list).order_by('-public_day')
        book_list = Book.objects.filter(id__in=id_book).order_by('-public_day')

    # Phân trang Story
    paginator = Paginator(story_list, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Phân trang Book
    paginator = Paginator(book_list, 6)
    page_number = request.GET.get('page')
    page_obj_book = paginator.get_page(page_number)
    return render(request, 'Do_an_01/search.html', {
        'story_list': story_list,
        'book_list': book_list,
        'keyword': tu_khoa,
        'list_category': list_category,
        'story_newest_14': story_newest_14,
        'page_obj': page_obj,
        'page_obj_book': page_obj_book,
        'session_info': session_info,
        'session_status': session_status,
    })

def storys_service(request):
    products = Story.objects.order_by('-public_day')
    result_list = list(products.values())
    return JsonResponse(result_list, safe=False)

def story_service(request, pk):
    story = Story.objects.filter(id=pk)
    result = list(story.values())[0]
    return JsonResponse(result, safe=False)


class StorytViewSet(viewsets.ModelViewSet):
    queryset = Story.objects.all().order_by('-public_day')
    serializer_class = StorySerializer
    # permission_classes = [permissions.IsAuthenticatedOrReadOnly]  # Chỉ đọc
    permission_classes = [permissions.IsAdminUser]  # Đọc / Ghi

Do_an_01/templates/Do_an_01/Masterbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% block title %}
        <title>Tin tức, mua bán, cho thuê nhà đất, thể thao, giải trí.</title>
    {% endblock %}
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href={% static 'img/favicon.ico' %} rel="icon">
    <link href="{% static 'img/favicon -copy.png' %}" rel="apple-touch-icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href={% static 'lib/owlcarousel/assets/owl.carousel.min.css' %} rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href={% static 'css/style.css' %} rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        jQuery(function ($) {
            let path = window.location.href;
            $('.mn a').each(function () {
                if (this.href === path) {
                    $(this).addClass('active')
                }
            });
        });
    </script>
</head>

<body>
{% url 'Do_an_01:index' as index %}
{% url 'Do_an_01:contact' as contact %}
{% url 'Do_an_01:single' as single %}
{% url 'Do_an_01:category' as category %}

<!-- Topbar Start -->
<div class="container-fluid d-none d-lg-block">
    <div class="row align-items-center bg-dark px-lg-5">
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-sm bg-dark p-0">
                <ul class="navbar-nav ml-n2">
                    <li class="nav-item border-right border-secondary">
                        <a class="nav-link text-body small" id="date" href="#"></a>
                    </li>
                    <li class="nav-item border-right border-secondary mn">
                        <a class="nav-link text-body small" href="{% url 'Do_an_01:contact' %}">Liên hệ</a>
                    </li>
                    <li class="nav-item mn">
                        {% if session_status %}
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-body small "
                                   data-toggle="dropdown">{{ session_info.ho }} {{ session_info.ten }}</a>
                                <div class="dropdown-menu ">
                                    <a href="{% url 'customers_hdg:my_account' %}"
                                       class="dropdown-item text-body small">Thông tin người dùng</a>
                                    <a href="{% url 'customers_hdg:logout' %}" class="dropdown-item  text-body small">Thoát</a>
                                </div>
                            </div>
                        {% else %}
                            <a class="nav-link text-body small" href="{% url 'customers_hdg:login' %}">Đăng nhập</a>
                        {% endif %}
                    </li>
                </ul>

            </nav>

        </div>

    </div>
    <div class="row align-items-center bg-white py-3 px-lg-5">
        <div class="col-lg-5">
            <a href="{% url 'Do_an_01:index' %}" class="navbar-brand p-0 d-none d-lg-block">
                <h1 class="m-0 display-4 text-uppercase text-primary">PHÚ YÊN<span
                        class="text-secondary">-NEWS</span></h1>
            </a>
        </div>
        <div  class="carousel slide col-lg-7 text-center text-lg-right" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#" data-slide-to="0" class="active"></li>
                <li data-target="#" data-slide-to="1"></li>
                <li data-target="#" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" >
                <div class="carousel-item active">
                    <a href="https://vnpt.vn"><img src={% static 'img/dl4.png' %} alt=""></a>
                </div>
                <div class="carousel-item">
                    <a href="https://vnpt.com.vn/di-dong"><img src={% static 'img/dl5.png' %} alt=""></a>
                </div>
                <div class="carousel-item">
                    <a href="https://vnpt.com.vn/goi-home"><img src={% static 'img/dl6.png' %} alt=""></a>
                </div>
            </div>
            <a class="carousel-control-prev" href="#" role="button" data-slide="prev" >
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#" role="button" data-slide="next" >
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
<!-- Topbar End -->
<!-- Navbar Start -->
<div class="container-fluid p-0">
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-lg-5">
        <a href="{% url 'Do_an_01:index' %}" class="navbar-brand d-block d-lg-none">
            <h1 class="m-0 display-4 text-uppercase text-primary">PHÚ YÊN<span
                    class="text-white font-weight-normal">-NEWS</span></h1>
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
            <div class="navbar-nav mr-auto py-0 text-primary ">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item mn">
                        <a class=" nav-link mn" href="{% url 'Do_an_01:index' %}">Trang chủ <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item mn">
                        <a class="nav-item nav-link mn" href="{% url 'Do_an_01:category' 1 %}">Nhà đất bán <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item mn">
                        <a class="nav-item nav-link mn" href="{% url 'Do_an_01:category' 2 %}">Nhà đất cho thuê <span
                                class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item mn">
                        <a class="nav-item nav-link mn" href="{% url 'Do_an_01:category' 8 %}">Du lịch <span
                                class="sr-only">(current)</span></a>
                    </li>
                    {#                    <a href="{% url 'Do_an_01:single'  11 %}" class="nav-item nav-link">Tin tức</a>#}
                    <div class="nav-item dropdown ">
                        <li class="nav-item mn">
                            <a class="nav-item nav-link mn" href="{% url 'Do_an_01:category' 7 %}">Dự án</a>
                        </li>
                    </div>
                    <li class="nav-item mn">
                        <a class="nav-item nav-link mn" href="{% url 'Do_an_01:contact' %}">Liên hệ <span
                                class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
            <form class="form-inline" method="get" action="{% url 'Do_an_01:search' %}">
                <div class="input-group ml-auto d-none d-lg-flex" style="width: 100%; max-width: 300px;">
                    <input type="text" class="form-control border-0" name="keyword" value="{{ keyword }}"
                           placeholder="Tìm kiếm" autocomplete="off" required="required">
                    <div class="input-group-append">
                        <button class="input-group-text bg-primary text-dark border-0 px-3">TÌM KIẾM
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </nav>
</div>
<!-- Navbar End -->
{% block content %}



{% endblock %}

<!-- Footer Start -->
<div class="container-fluid bg-dark pt-5 px-sm-3 px-md-5 mt-5">
    <div class="row py-4">
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Liên lạc</h5>
            <p class="font-weight-medium"><i class="fa fa-map-marker-alt mr-2"></i>Phường 12, Quận Gò Vấp, TP. Hồ Chí
                Minh</p>
            <p class="font-weight-medium"><i class="fa fa-phone-alt mr-2"></i>0982 98 67 68</p>
            <p class="font-weight-medium"><i class="fa fa-envelope mr-2"></i>huynhdonggiang@gmail.com</p>
            <div class="d-flex justify-content-start">
                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="#"><i class="fab fa-instagram"></i></a>
                <a class="btn btn-lg btn-secondary btn-lg-square" href="#"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Tin tức phổ biến</h5>
            {% for story in story_newest_3 %}
                <div class="mb-3">
                    <a class="small text-body font-weight-medium"
                       href="{% url 'Do_an_01:single' story.pk %}">{{ story.name|truncatewords:8 }}</a>
                </div>
            {% endfor %}

        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Thể loại</h5>
            <div class="m-n1">
                {% for list_category in list_category %}
                    <a href="{% url 'Do_an_01:category'  list_category.pk %}"
                       class="btn btn-sm btn-outline-secondary m-1">{{ list_category.name|truncatewords:10 }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="mb-4 text-white text-uppercase font-weight-bold">ẢNH FLICKR</h5>
            <div class="row">
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src={% static 'img/news-110x110-1.jpg' %} alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src={% static 'img/news-110x110-2.jpg' %} alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src={% static 'img/news-110x110-3.jpg' %} alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src={% static 'img/news-110x110-4.jpg' %} alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src={% static 'img/news-110x110-5.jpg' %} alt=""></a>
                </div>
                <div class="col-4 mb-3">
                    <a href=""><img class="w-100" src={% static 'img/news-110x110-1.jpg' %} alt=""></a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid py-4 px-sm-3 px-md-5" style="background: #111111;">
    <p class="m-0 text-center">&copy; <a href="#">Website</a>. Đã đăng ký bản quyền thiết ký bởi <a
            href="https://vnpt.vn">Huỳnh Đông Giang</a></p>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-primary btn-square back-to-top"><i class="fa fa-arrow-up"></i></a>

{% block script %}
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src={% static 'lib/easing/easing.min.js' %}></script>
    <script src={% static 'lib/owlcarousel/owl.carousel.min.js' %}></script>

    <!-- Template Javascript -->
    <script src={% static 'js/main.js' %}></script>
    <script>
        window.onload = setInterval(clock, 1000);

        function clock() {
            var d = new Date();
            var curHour = d.getHours();
            var curMinu = d.getMinutes();
            var curSecon = d.getSeconds();
            var date = d.getDate();
            var year = d.getFullYear();
            var month = d.getMonth();
            var monthArr = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"];
            month = monthArr[month];
            document.getElementById("date").innerHTML = "Ngày " + date + "/" + month + "/" + year + "-" + curHour + ":" + curMinu + ":" + curSecon;
        }
    </script>
{% endblock %}
</body>

</html>